Repository linebender/vello, pull requests merged in 2025-08, with the labels that each got.

#1161 Alternative API for image overrides
  vello/src/lib.rs
  vello/src/wgpu_engine.rs
Labels: C-classic

#1169 Bump skrifa to `v0.35.0`. Add Changelog entry for vello 0.5.1
  CHANGELOG.md
  Cargo.lock
  Cargo.toml
Labels: dependencies

#1174 vello_hybrid: remove suspending work from scheduler
  sparse_strips/vello_hybrid/src/schedule.rs
Labels: C-hybrid

#1178 vello_hybrid: add `mix` blend layer support
  sparse_strips/vello_dev_macros/src/test.rs
  sparse_strips/vello_hybrid/src/schedule.rs
  sparse_strips/vello_sparse_shaders/shaders/render_strips.wgsl
  sparse_strips/vello_sparse_tests/snapshots/mix_compose_combined_test_matrix.png
  sparse_strips/vello_sparse_tests/snapshots/mix_modes_non_gradient_test_matrix.png
  sparse_strips/vello_sparse_tests/tests/compose.rs
  sparse_strips/vello_sparse_tests/tests/mix.rs
Labels: C-hybrid

#1185 Upgrade skrifa to 0.36
  Cargo.lock
  Cargo.toml
Labels: dependencies
